name: Run R script daily

# Schedule the workflow to run every day at midnight UTC
on:
  schedule:
    - cron: '38 19 * * *'  # This runs daily at midnight UTC (adjust as needed)

# Define the workflow jobs
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgsl-dev libboost-dev libcurl4-openssl-dev
        gsl-config --libs
        gsl-config --cflags

    - name: Cache renv library
      uses: actions/cache@v3
      with:
        path: renv/library
        key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    # Step 3: Install R package dependencies (if any)
    - name: Install R package dependencies
      run: |
        install.packages("renv")
        renv::restore()  # Restores packages from the lockfile (if using renv)
      shell: Rscript {0}

    - name: Run R script
      run: |
        Rscript run.R

    # Step 5: Save the results (as an artifact)
    - name: Upload results as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: benchmark-tree-regressions/res-action.rds  # This should point to where the results are saved
